### ISSUE TITLE
Running a job with debug logging should enable debug output by the GitHub Action

### ISSUE THREAD

**Issue by ari-becker** [teleport-actions/root#35]
See:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

When debug logging is enabled by the user, and therefore the `RUNNER_DEBUG` environment variable is set, the action does not understand that debug logging was requested and thus add the `--debug` flag to the `tbot` call.

When the user enables debug logging, the `tbot` call should include the `--debug` flag, thus printing debug logging to the GitHub Actions job.

<img width="630" alt="image" src="https://github.com/teleport-actions/root/assets/1388505/77e7df3d-7505-4d13-891e-6053ee1de9ef">
<img width="1282" alt="image" src="https://github.com/teleport-actions/root/assets/1388505/9999175a-7edf-46da-b2dc-829ee563e298">
<img width="772" alt="image" src="https://github.com/teleport-actions/root/assets/1388505/5a6a2fb5-5f96-4222-9522-bebc574579ca">

**Comment by strideynet** [comment]
👍  Yup - this is a good idea. It looks like we're halfway to implementing this anyway. I'll add this now.

**Comment by strideynet** [comment]
v1.1.3 of the actions includes this fix - pushing it out now.
